export const AI_AGENTS = [
  {
    id: 'content-manager',
    name: 'Content Strategy Manager',
    slug: 'content-manager',
    role: 'content_manager',
    description: 'Manages content strategy, blog posts, and SEO optimization',
    capabilities: ['blog_writing', 'seo_optimization', 'content_calendar', 'keyword_research'],
    icon: '✍️',
  },
  {
    id: 'social-manager',
    name: 'Social Media Manager',
    slug: 'social-manager',
    role: 'social_manager',
    description: 'Handles social media posts, engagement, and growth',
    capabilities: ['post_creation', 'hashtag_research', 'engagement_tracking', 'content_scheduling'],
    icon: '📱',
  },
  {
    id: 'email-manager',
    name: 'Email Marketing Manager',
    slug: 'email-manager',
    role: 'email_manager',
    description: 'Manages email campaigns, sequences, and automation',
    capabilities: ['email_writing', 'sequence_creation', 'list_management', 'campaign_tracking'],
    icon: '📧',
  },
  {
    id: 'operations-manager',
    name: 'Operations Manager',
    slug: 'operations-manager',
    role: 'operations_manager',
    description: 'Oversees workflows, automations, and system health',
    capabilities: ['workflow_automation', 'system_monitoring', 'task_delegation', 'process_optimization'],
    icon: '⚙️',
  },
  {
    id: 'lead-manager',
    name: 'Lead Generation Manager',
    slug: 'lead-manager',
    role: 'lead_manager',
    description: 'Finds, validates, and nurtures leads',
    capabilities: ['lead_finding', 'email_validation', 'outreach_automation', 'lead_scoring'],
    icon: '🎯',
  },
  {
    id: 'video-manager',
    name: 'Video Production Manager',
    slug: 'video-manager',
    role: 'video_manager',
    description: 'Creates video content and manages video workflows',
    capabilities: ['video_generation', 'script_writing', 'thumbnail_creation', 'video_editing'],
    icon: '🎬',
  },
];

export const WORKFLOWS = [
  {
    id: 'midnight-magic',
    name: 'Midnight Magic',
    description: 'Daily automated builds at 1AM/3AM',
    schedule: '0 1,3 * * *',
    type: 'scheduled',
    status: 'active',
  },
  {
    id: 'shopify-sync',
    name: 'Shopify Store Sync',
    description: 'Sync product data and metafields',
    schedule: '0 */6 * * *',
    type: 'scheduled',
    status: 'active',
  },
  {
    id: 'daily-briefing',
    name: 'Daily Briefing Generator',
    description: 'Generate daily summary and insights',
    schedule: '0 6 * * *',
    type: 'scheduled',
    status: 'active',
  },
  {
    id: 'lead-hunter',
    name: 'Lead Hunter',
    description: 'Find and validate email leads',
    schedule: null,
    type: 'manual',
    status: 'pending',
  },
  {
    id: 'content-forge',
    name: 'Content Forge',
    description: 'Generate Instagram content',
    schedule: null,
    type: 'manual',
    status: 'active',
  },
  {
    id: 'seo-blogs',
    name: 'SEO Blog Generator',
    description: 'Create keyword-optimized blog posts',
    schedule: null,
    type: 'manual',
    status: 'active',
  },
];

export const REVENUE_TARGETS = {
  annual: 490000,
  monthly: 40833,
  currentMonth: 12500,
  progress: 30.6,
};
